### ISSUE TITLE
Install and run the game ?

### ISSUE THREAD

**Issue by zilveer** [ginuerzh/poker#1]
Hello,
How can I install this and run it?

Also does it have any database ?

Regards

**Comment by ginuerzh** [comment]
This is an experimental project, the client/server examples are in server/examples.
You can drop out the dependencies with some modification.

**Comment by TurEduard** [comment]
Fuck, are you serious?!! You can say how run you code from A to Z?

**Comment by zilveer** [comment]
@ginuerzh
I understand but I still don't understand how to run it.

Thanks for any response


Regards

**Comment by ginuerzh** [comment]
I have updated the code, and the DB dependency has been removed.
Now you can compile and run the server example:

```bash
$ cd server/examples/server
$ go build
$ ./server
```
Then open the `Poker/index.html` in your browser.

**Comment by zilveer** [comment]
@ginuerzh thank you very much for the installation instructions.

Regards
